name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PHP linter
        run: npm run lint

      - name: Docker-Compose build
        run: cp .env.test .env && docker-compose build

      - name: Docker-Compose up
        run: docker-compose up -d

      - name: frontend install
        run: docker-compose exec frontend yarn install

      - name: frontend lint
        run: docker-compose exec frontend yarn lint

      - name: frontend build
        run: docker-compose exec frontend yarn build

      - name: Test Server
        run: docker-compose exec laravel.test php artisan test
