name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - php-lint-ci

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PHP linter
        run: |
          sh ./php-lint.sh
          if [ $? -ne 0 ]; then
            exit 1
          fi